name: Build and deploy Angular SSR app to Azure Web App - oneticket-web-eas-dev01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' # Use LTS version for better Angular compatibility

      - name: Install dependencies and build SSR
        run: |
          npm ci # Use package-lock.json for consistent installs
          npm run build:ssr # Builds both browser and server bundles
        env:
          CI: true # Avoids Angular CLI prompts

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            dist/OneTicketPortal/ # SSR build output (browser and server folders)
            package.json
            package-lock.json # Ensures consistent dependency installation

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'oneticket-web-eas-dev01'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AD617C2BF04442BAA308E866A4D1DCC6 }}

